# This is a basic workflow to help you get started with Actions

name: Generate image

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
 
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wkhtmltopdf=0.12.4-1
          sudo apt-get install xvfb=2:1.19.6-1ubuntu4.8

      - name: Install pip dependencies
        run: |
          python -m pip install pip==20.3.3
          pip install -r requirements.txt

      - name: Run entrypoint
        run: generate_image
        env:
          X_RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Show latest files
        run: echo "GENERATED_IMAGE=$(ls -t /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/wotdb/data/ | head -1)" >> $GITGUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: generated_image
          path: /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/wotdb/data/$GENERATED_IMAGE
