# This is a basic workflow to help you get started with Actions

name: Twitter post checker

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 20 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Check account
        run: |
          ENDPOINT='https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=WordOfTheDay_B&count=1'
          RESPONSE=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}" "$ENDPOINT")
          echo RESPONSE=$RESPONSE
          CREATED_AT=$(echo $RESPONSE | jq '.[0].created_at' | sed 's/"//g')
          echo CREATED_AT=$CREATED_AT
          CREATED_AT_DAY=$(date -d "$CREATED_AT" +'%d')
          echo CREATED_AT_DAY=$CREATED_AT_DAY
          TODAY=$(date +'%d')
          echo TODAY=$TODAY
          if [ $CREATED_AT_DAY == $TODAY ]; then
            echo 'There was a post today. All good.';
          else
            echo 'There was no post today! Exiting to trigger email!';
            exit 1;
          fi
