# This is a basic workflow to help you get started with Actions
name: Twitter schedule

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 12 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
 
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wkhtmltopdf=0.12.4-1 xvfb=2:1.19.6-1ubuntu4.8

      - name: Install pip dependencies
        run: |
          python -m pip install pip==20.3.1
          pip install -r requirements.txt

      - name: Run entrypoint
        run: twitter_post
        env:
          X_RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }}

      - name: Retrieve data directory
        run: |
            COMMAND="import sysconfig; print(sysconfig.get_path('purelib'))"
            DATA_DIRECTORY=$(python3 -c "$COMMAND")/$(show_data_folder)/
            echo "DATA_DIRECTORY=$DATA_DIRECTORY" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: "${{ env.DATA_DIRECTORY }}"
